name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Linker.App.sln

      - name: Build
        run: dotnet build src/Linker.App.sln -c Release --no-restore

      - name: Run Tests
        run: dotnet test src/Linker.App.sln --configuration Release --verbosity normal

