name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/EventStore.Tools.Linker.sln

      - name: Build
        run: dotnet build src/EventStore.Tools.Linker.sln -c Release --no-restore

      - name: Run Tests
        run: dotnet test src/EventStore.Tools.Linker.sln --no-build --verbosity normal
